/** @type {import('prettier').Config} */
module.exports = {
	endOfLine: 'lf',
	semi: true,
	jsxSingleQuote: true,
	trailingComma: 'none',
	bracketSpacing: true,
	bracketSameLine: false,
	singleQuote: true,
	useTabs: true,
	arrowParens: 'always',
	tabWidth: 2,
	trailingComma: 'es5',
	importOrder: [
		'^(react/(.*)$)|^(react$)',
		'^(next/(.*)$)|^(next$)',
		'<THIRD_PARTY_MODULES>',
		'',
		'^types$',
		'^@/types/(.*)$',
		'^@/config/(.*)$',
		'^@/lib/(.*)$',
		'^@/hooks/(.*)$',
		'^@/components/ui/(.*)$',
		'^@/components/(.*)$',
		'^@/styles/(.*)$',
		'^@/app/(.*)$',
		'',
		'^[./]',
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	// FIX: Plugins work in vscode but not in neovim (null-ls). Update: works with prettierrd (tailwind plugin only)
	plugins: [
		'@ianvs/prettier-plugin-sort-imports',
		require('prettier-plugin-tailwindcss'),
	],
};
